---
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
featureGates:
  APIServerTracing: true
nodes:
  - role: control-plane
    image: kindest/node:v1.30.0
    extraMounts:
      - hostPath: ./app/api-server/
        containerPath: /api-server
        readOnly: true
    kubeadmConfigPatches:
      - |
        kind: KubeletConfiguration
        apiVersion: kubelet.config.k8s.io/v1beta1
        featureGates:
          KubeletTracing: true
        tracing:
          samplingRatePerMillion: 1.0
          endpoint: "127.0.0.1:4317"
      - |
        kind: ClusterConfiguration
        etcd:
          local:
            imageRepository: "quay.io/coreos"
            imageTag: "v3.5.11"
            extraArgs:
              experimental-enable-distributed-tracing: "true"
              experimental-distributed-tracing-address: "127.0.0.1:4317"
              experimental-distributed-tracing-service-name: "etcd"
              experimental-distributed-tracing-instance-id: "caf201fd-8d5b-467b-a70f-09ad3beb5a21"
              experimental-distributed-tracing-sampling-rate: "1000000"
        apiServer:
          extraArgs:
            tracing-config-file: "/api-server/tracing-config.yaml"
          extraVolumes:
            - name: tracing-config
              hostPath: /api-server/tracing-config.yaml
              mountPath: /api-server/tracing-config.yaml
              readOnly: true
              pathType: "File"